[install]
hoist = true

[alias]
"@cmmv/core" = "./packages/core"
"@cmmv/core/*" = "./packages/core/*"
"@cmmv/http" = "./packages/http"
"@cmmv/http/*" = "./packages/http/*"
"@cmmv/protobuf" = "./packages/protobuf"
"@cmmv/protobuf/*" = "./packages/protobuf/*"
"@cmmv/view" = "./packages/view"
"@cmmv/view/*" = "./packages/view/*"
"@cmmv/ws" = "./packages/ws"
"@cmmv/ws/*" = "./packages/ws/*"
"@cmmv/repository" = "./packages/repository"
"@cmmv/repository/*" = "./packages/repository/*"
"@cmmv/cache" = "./packages/cache"
"@cmmv/cache/*" = "./packages/cache/*"
"@cmmv/scheduling" = "./packages/scheduling"
"@cmmv/scheduling/*" = "./packages/scheduling/*"
"@cmmv/auth" = "./packages/auth"
"@cmmv/auth/*" = "./packages/auth/*"
"@cmmv/testing" = "./packages/testing"
"@cmmv/testing/*" = "./packages/testing/*"
"@cmmv/form" = "./packages/form"
"@cmmv/form/*" = "./packages/form/*"
"@models" = "./src/models"
"@models/*" = "./src/models/*"
"@modules" = "./src/modules"
"@modules/*" = "./src/modules/*"
"@services" = "./src/services"
"@services/*" = "./src/services/*"
"@controllers" = "./src/controllers"
"@controllers/*" = "./src/controllers/*"
"@contracts" = "./src/contracts"
"@contracts/*" = "./src/contracts/*"
"@entities" = "./src/entities"
"@entities/*" = "./src/entities/*"
"@gateways" = "./src/gateways"
"@gateways/*" = "./src/gateways/*"
"@protos" = "./src/protos"
"@protos/*" = "./src/protos/*"
"@generated" = "./.generated"
"@generated/*" = "./.generated/*"
"@g" = "./.generated"
"@g/*" = "./.generated/*"
