export declare function Controller(prefix?: string): ClassDecorator;
export declare function Get(path?: string, cb?: Function): MethodDecorator;
export declare function Post(path?: string, cb?: Function): MethodDecorator;
export declare function Put(path?: string, cb?: Function): MethodDecorator;
export declare function Delete(path?: string, cb?: Function): MethodDecorator;
export declare function Patch(path?: string, cb?: Function): MethodDecorator;
export declare function Body(): ParameterDecorator;
export declare function Queries(): ParameterDecorator;
export declare function Param(paramName: string): ParameterDecorator;
export declare function Query(queryName: string): ParameterDecorator;
export declare function Header(headerName: string): ParameterDecorator;
export declare function Headers(): ParameterDecorator;
export declare function Request(): ParameterDecorator;
export declare function Req(): ParameterDecorator;
export declare function Response(): ParameterDecorator;
export declare function Res(): ParameterDecorator;
export declare function Next(): ParameterDecorator;
export declare function Session(): ParameterDecorator;
export declare function Ip(): ParameterDecorator;
export declare function HostParam(): ParameterDecorator;
